---
- name: install Python XML support (Python 2)
  become: yes
  package:
    name: python-lxml
    state: present
  when: "intellij_plugins_python_major_version == '2'"

- name: install Python XML support (Python 3)
  become: yes
  package:
    name: "python3-lxml"
    state: present
  when: "intellij_plugins_python_major_version == '3'"

- name: install plugins
  become: yes
  intellij_plugins_install:
    plugin_manager_url: '{{ intellij_plugins_manager_url }}'
    intellij_home: '{{ intellij_plugins_intellij_home }}'
    intellij_user_plugins_dir: '{{ intellij_plugins_intellij_user_plugins_dir }}'
    username: '{{ item.0.username }}'
    plugin_id: '{{ item.1 }}'
    download_cache: '{{ intellij_plugins_download_dir }}'
  with_subelements:
    - '{{ users }}'
    - intellij_plugins
    - skip_missing: yes
  loop_control:
    label: '{{ item.0.username }}: {{ item.1 }}'
