---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-intellij-plugins-ultimate-ubuntu
    groups:
      - ultimate
    image: ubuntu:16.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  inventory:
    group_vars:
      ultimate:
        intellij_edition: ultimate

verifier:
  name: testinfra
  directory: ../default/tests
