---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-intellij-plugins-community-centos-7
    groups:
      - community
    image: centos:7

provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  inventory:
    group_vars:
      community:
        intellij_edition: community
        intellij_plugins_intellij_home: '/opt/idea/idea-community-2018.2'
        intellij_plugins_intellij_user_dirname: '.IdeaIC2018.2'
  lint:
    name: ansible-lint

scenario:
  name: centos

verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
