---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-intellij-plugins-community-rocky
    groups:
      - community
    image: rockylinux/rockylinux:8
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  inventory:
    group_vars:
      community:
        intellij_edition: community

verifier:
  name: testinfra
  directory: ../default/tests
