---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: "ansible_pkg_mgr == 'apt'"

    - name: install find (dnf)
      dnf:
        name: findutils
        state: present
      when: "ansible_pkg_mgr == 'dnf'"

    - name: create test users
      become: yes
      user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr
        - test_usr2

  roles:
    - role: gantsign.intellij

    - role: ansible-role-intellij-plugins
      users:
        - username: test_usr
          intellij_plugins:
            - google-java-format
            - MavenRunHelper
            - com.dubreuia
        - username: test_usr2
