---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-intellij-plugins-community-default
    groups:
      - community
    image: ubuntu:20.04

provisioner:
  name: ansible
  inventory:
    group_vars:
      community:
        intellij_edition: community

verifier:
  name: testinfra
